Update Environment for Pagination
metadew/iesi-api-documentation pull request #22
Opened 2021-07-26 07:52 UTC by Suyash-d

**Is your feature request related to a problem? Please describe.**

Create Pagination request of Environment for Open API documentation.

2021-08-02 13:09 UTC, BerrevoetsRobbe requested changes

2021-08-02 13:09 UTC, BerrevoetsRobbe commented on src/paths/environments/fetchAll.yaml
>      description: Expected response to a valid request
"../../schemas/environments/EmbeddedEnvironmentDto.yaml"
should be modified as well. Did you visually confirm the layout?

2021-08-05 08:01 UTC, BerrevoetsRobbe requested changes

2021-08-05 08:01 UTC, BerrevoetsRobbe commented on src/paths/environments/fetchAll.yaml
>      description: Expected response to a valid request
response does not contain pagination information. have a look at src/paths/scripts/fetchAll.yaml for inspiration

2021-08-05 08:08 UTC, BerrevoetsRobbe commented on src/paths/environments/fetchAll.yaml
>      description: Expected response to a valid request
src/schemas/scripts/PagedScriptDto.yaml

2021-08-09 07:21 UTC, BerrevoetsRobbe approved these changes

2021-08-09 07:22 UTC, BerrevoetsRobbe commented
linked to metadew/iesi#352

2021-08-12 12:53 UTC, Suyash-d commented
**This PR to be merged in this branch before merged to develop [Unpaginated Get Endpoint for Environment #24]**(https://github.com/metadew/iesi-api-documentation/pull/24)

2021-08-13 07:35 UTC, BerrevoetsRobbe commented
don't forget to build and push the build openapi.yaml

2021-08-16 08:53 UTC, Suyash-d commented
@BerrevoetsRobbe Please merge to develop, [fetch all environments unpaginated](https://github.com/metadew/iesi/pull/368) merged to this branch.

2021-08-16 11:38 UTC, BerrevoetsRobbe approved these changes

2021-08-16 14:53 UTC, merged